import 'package:flutter/material.dart';

class NewTransaction extends StatelessWidget {
  final Function addTx;
  final titleController = TextEditingController();
  final amountController =
      TextEditingController(); //Resolves Warning generated by stateless widget as data is changing

  NewTransaction(this.addTx);

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: EdgeInsets.all(5),
      child: Container(
        margin: EdgeInsets.all(15),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            TextField(
              decoration: InputDecoration(labelText: "Title"),
              controller: titleController,
            ),
            TextField(
              decoration: InputDecoration(labelText: "Amount"),
              controller: amountController,
            ),
            RaisedButton(
              child: Text("Add"),
              onPressed: () {
                addTx(
                    titleController.text, double.parse(amountController.text));
              },
              elevation: 1.5,
              color: Colors.green,
            )
          ],
        ),
      ),
    );
  }
}
