import 'package:flutter/material.dart';

class NewTransaction extends StatelessWidget {
  final titleController = TextEditingController();
  final amountController =
      TextEditingController(); //Resolves Warning generated by stateless widget as data is changing
  @override
  Widget build(BuildContext context) {
    return Card(
      margin: EdgeInsets.all(5),
      child: Container(
        margin: EdgeInsets.all(15),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            TextField(
              decoration: InputDecoration(labelText: "Title"),
              // onChanged: (val) {
              //   titleInput = val;
              // },
              controller: titleController,
            ),
            TextField(
              decoration: InputDecoration(labelText: "Amount"),
              // onChanged: (val) {
              //   amountInput = val;
              // },
              controller: amountController,
            ),
            RaisedButton(
              child: Text("Add"),
              onPressed: () {
                // print(titleInput);
                // print(amountInput);
                print(titleController);
                print(amountController);
              },
              elevation: 1.5,
              color: Colors.green,
            )
          ],
        ),
      ),
    );
  }
}
